<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;


class AdvertisingNotice extends Model
{
    public function save(array $options = [])
    {
        if ($this->status == 'published'){
            self::where('status', 'published')->update(['status' => 'unpublished']);
        }
        return parent::save($options); // TODO: Change the autogenerated stub
    }
}
